# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('max_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
